/* (c) 2017, JDMCreator, V 1.5*/
(function(n,B){var k=n.document,w=/^[a-z]+/i,x=/([.]{1}[^\[#.]+)|(#{1}[^\[#.]+)|(\[[ ]*\^?[ ]*[a-z_-]+[ ]*\])|(\[[ ]*\^?[ ]*[a-z_-]+[ ]*=[^\]]+\])/gi,q=/\[\s*name\s*=([^\]]+)\]/gi,y=/^\[[ ]?([\s\S]*)[ ]?\]$/i,r=/\[[ ]*(\^?)[ ]*([a-z_-]+)[ ]*=[ ]*([^\]]+)/gi,t=/^\x3c!--([\S\s]*)--\x3e$/gi,u=String.prototype.trim,p=function(c){return u?u.call(c):c.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},z=function(c){return c.replace(/(\-[a-z])/g,function(b){return b.toUpperCase().replace("-","")})};try{k.createElement("<input name='test'>");
var v=!0}catch(c){v=!1}isASingleton=function(c){return-1!="|base|br|col|command|embed|hr|img|input|link|meta|param|source|".indexOf("|"+c+"|")};xCreateElement=function(c,b,a,e){if(1!=b.nodeType)return b;var g=b.style;c=b.tagName.toLowerCase();if("style"==c&&(a.content||a.text||a.css)){var d=a.css||a.content||a.text;if(b.styleSheet)b.styleSheet.cssText=d;else{var f=b.cloneNode(!0);k.createElement("head").appendChild(f);f.styleSheet?(f.styleSheet.cssText=d,b=f.parentNode.removeChild(f)):b.appendChild(k.createTextNode(d))}}else if("script"==
c&&(a.script||a.content||a.text))b.text=a.script||a.content||a.text;else if(!a.html&&!a.content||isASingleton(c))if(a.text&&!isASingleton(c))try{b.appendChild(k.createTextNode(a.text))}catch(A){}else!a.content||"input"!=c&&"textarea"!=c||(a.defaultValue=a.value||content);else try{if("tr"==c&&b.outerHTML)for(d=k.createElement("div"),d.innerHTML="<table><tbody><tr>"+(a.html||a.content)+"</tr></tbody></table>",d=d.getElementsByTagName("tr")[0];d.firstChild;)b.appendChild(d.firstChild);else b.innerHTML=
a.html||a.content,"pre"==c&&(b.innerHTML=b.innerHTML)}catch(A){try{for(d=k.createElement("div"),d.innerHTML=a.html||a.content;d.firstChild;)b.appendChild(d.firstChild)}catch(C){}}if(a.style||a.cssText||a.css&&"style"!=c)d=a.style||a.cssText||a.css,b.setAttribute("style",d),g.cssText=d;a.value&&("input"==c||"textarea"==c?(b.value=a.value,b.defaultValue=a.value):"option"==c&&(b.value=a.value));a.title&&(b.title=a.title);if(a.src||a.href)g=k.createElement("a"),g.href=a.src||a.href,a.src?b.src=g.href:
b.href=g.href;if(a.on){f=a.on;d=f.constructor.prototype;g=f.hasOwnProperty;for(var h in f)if(g&&g.call(f,h)||d[h]!==f[h])if(a.jQuery&&(typeof a.jQuery==typeof Function()||n.jQuery))(a.jQuery=typeof a.jQuery==typeof Function()?a.jQuery:n.jQuery).on(h,f[h]);else b.addEventListener?b.addEventListener(h,f[h],!1):b.attachEvent&&b.attachEvent("on"+event,function(a,b){return function(){a.call(b)}}(f[h],b))}if(a.attr)for(h in f=a.attr,d=f.constructor.prototype,g=f.hasOwnProperty,f)if(g&&g.call(f,h)||d[h]!==
f[h])e||"input"==c&&"name"==h.toLowerCase()||setAttribute(b,h,f[h]);if(a.childNodes)for(e=a.childNodes,e="[object Array]"===Object.prototype.toString.call(e)?e:[e],h=0,g=e.length;h<g;h++)if(d=e[h],"[object Array]"===Object.prototype.toString.call(d)?d=DOMBuilder(d[0],d[1]):d.toString()===d&&(d=DOMBuilder(d)),"table"==c&&!1!==a.tableBeautifier&&0!==a.tableBeautifier){var l=b.firstChild,m=d.tagName;-1!="|TBODY|THEAD|TFOOT|".indexOf("|"+m+"|")||8==d.nodeType?b.appendChild(d):"COLGROUP"==m||"CAPTION"==
m?b.insertBefore(d,l):(l&&-1!="|TBODY|THEAD|TFOOT|".indexOf("|"+l.tagName+"|")||(l=b.appendChild(k.createElement("tbody"))),"TR"==m?l.appendChild(d):((f=l.firstChild)&&"TR"==f.tagname||(f=l.appendChild(k.createElement("tr"))),"TD"==m||"TH"==m?f.appendChild(d):((l=f.firstChild)&&"TD"==l.tagName&&"TH"==l.tagName||(l=f.appendChild(k.createElement("td"))),l.appendChild(d))))}else b.appendChild(d);return a.documentFragment||a.fragment?(a=k.createDocumentFragment(),a.appendChild(b),a):b};setAttribute=function(c,
b,a){b=p(b.toLowerCase());if(/^data-/.test(b))c.dataset?c.dataset[z(b.substring(5))]=a:c.setAttribute(b,a);else if(/^on/.test(b)){c.setAttribute(b,a);try{c[b]=new Function(a)}catch(g){}}else if(-1!="|style|class|classname|type|for|htmlfor|".indexOf("|"+b+"|"))switch(b){case "style":c.setAttribute(b,a);c.style.cssText=a;break;case "class":case "classname":if(c.classList){b=a.split(/\s+/g);for(var e=0;e<b.length;e++)c.classList.add(b[e])}else c.className=a;case "type":c.type=a;break;case "for":case "htmlfor":c.htmlFor=
a;break;default:c.setAttribute(b,a,0)}else c.setAttribute(b,a,0)};getName=function(c,b){var a="";if(b&&b.attr){var e=b.attr;for(var g in e)if("name"==g.toLowerCase()&&e.hasOwnProperty(g))return e[g]}for(q.lastIndex=0;e=q.exec(c);)a=e[1];a&&(a=p(a),e=a.charAt(0),"'"!=e&&'"'!=e||a.charAt(a.length-1)!=e||(a=a.substring(1,a.length-1)));return a};DOMBuilder=function(c,b){c=p(c||"");if(!c)return null;t.lastIndex=0;var a=t.exec(c);var e=c.charAt(0);if(a&&a[1])e=k.createComment(""),e.nodeValue=a[1];else if('"'!=
e&&"'"!=e||c.charAt(c.length-1)!=e){a=w.exec(c)||["div"];e=k.createElement(a[0]);var g=!1;if("input"==a.toString().toLowerCase()&&v&&(a=getName(c,b)))try{if(e=k.createElement('<input name = "'+a+'" >'),g=!0,"INPUT"!=e.tagName)throw 0;}catch(l){e=k.createElement("input"),e.name=a}for(;a=x.exec(c);)if(a[1])a=a[1].substring(1),e.classList?e.classList.add(a):e.className=e.className?e.className+(" "+a):a;else if(a[2])e.id=a[2].substring(1);else if(a[3])(a=y.exec(a[3]))&&a[1]&&(a=a[1],setAttribute(e,a,
a));else if(a[4]){r.lastIndex=0;var d=r.exec(a[4]);a=(d[1]?"data-":"")+d[2];d=d[3];var f=d.charAt(0),h=d.charAt(d.length-1);"'"!=f&&'"'!=f||f!==h||(d=d.substring(1,d.length-1));(!g||"name"!=a.toLowerCase()&&"INPUT"!=e.tagName)&&setAttribute(e,a,d)}}else e=k.createTextNode(c.substring(1,c.length-1));b&&b.toString()===b&&(b={content:b});b&&xCreateElement&&(e=xCreateElement(c,e,b,g));return e};n.DOMBuilder=DOMBuilder})(window);