/* (c) 2014, JDMCreator, V 1.4*/
(function(m,z){var k=m.document,v=/^[a-z]+/i,w=/([.]{1}[^\[#.]+)|(#{1}[^\[#.]+)|(\[[ ]*\^?[ ]*[a-z_-]+[ ]*\])|(\[[ ]*\^?[ ]*[a-z_-]+[ ]*=[^\]]+\])/gi,p=/\[\s*name\s*=([^\]]+)\]/gi,x=/^\[[ ]?([\s\S]*)[ ]?\]$/i,s=/\[[ ]*(\^?)[ ]*([a-z_-]+)[ ]*=[ ]*([^\]]+)/gi,t=/^\x3c!--([\S\s]*)--\x3e$/gi,u=String.prototype.trim,q=function(c){u&&u.call(c);c=c.replace(/^\s\s*/,"");for(var b=/\s/,a=c.length;b.test(c.charAt(--a)););return c.slice(0,a+1)},y=function(c){return c.replace(/(\-[a-z])/g,function(b){return b.toUpperCase().replace("-",
"")})},r;try{k.createElement("<input name='test'>"),r=!0}catch(A){r=!1}isASingleton=function(c){return-1!="|base|br|col|command|embed|hr|img|input|link|meta|param|source".indexOf("|"+c+"|")};xCreateElement=function(c,b,a,d){if(1!=b.nodeType)return b;var g=b.style;c=b.tagName.toLowerCase();if("style"==c&&(a.content||a.text||a.css)){var e=a.css||a.content||a.text;if(b.styleSheet)b.styleSheet.cssText=e;else{var f=b.cloneNode(!0);k.createElement("head").appendChild(f);f.styleSheet?(f.styleSheet.cssText=
e,b=f.parentNode.removeChild(f)):b.appendChild(k.createTextNode(e))}}else if("script"==c&&(a.script||a.content||a.text))b.text=a.script||a.content||a.text;else if(!a.html&&!a.content||isASingleton(c))if(a.text&&!isASingleton(c))try{b.appendChild(k.createTextNode(a.text))}catch(r){}else!a.content||"input"!=c&&"textarea"!=c||(a.defaultValue=a.value||content);else try{if("tr"==c&&b.outerHTML)for(e=k.createElement("div"),e.innerHTML="<table><tbody><tr>"+(a.html||a.content)+"</tr></tbody></table>",e=e.getElementsByTagName("tr")[0];e.firstChild;)b.appendChild(e.firstChild);
else b.innerHTML=a.html||a.content,"pre"==c&&(b.innerHTML=b.innerHTML)}catch(B){try{for(e=k.createElement("div"),e.innerHTML=a.html||a.content;e.firstChild;)b.appendChild(e.firstChild)}catch(q){}}if(a.style||a.cssText||a.css&&"style"!=c)e=a.style||a.cssText||a.css,b.setAttribute("style",e),g.cssText=e;a.value&&("input"==c||"textarea"==c?(b.value=a.value,b.defaultValue=a.value):"option"==c&&(b.value=a.value));a.title&&(b.title=a.title);if(a.src||a.href)g=k.createElement("a"),g.href=a.src||a.href,a.src?
b.src=g.href:b.href=g.href;if(a.on){var f=a.on,g=f.constructor.prototype,e=f.hasOwnProperty,h;for(h in f)if(e&&e.call(f,h)||g[h]!==f[h])if(a.jQuery&&(typeof a.jQuery==typeof Function()||m.jQuery))(a.jQuery=typeof a.jQuery==typeof Function()?a.jQuery:m.jQuery).on(h,f[h]);else b.addEventListener?b.addEventListener(h,f[h],!1):b.attachEvent&&b.attachEvent("on"+event,function(a,b){return function(){a.call(b)}}(f[h],b))}if(a.attr)for(h in f=a.attr,g=f.constructor.prototype,e=f.hasOwnProperty,f)if(e&&e.call(f,
h)||g[h]!==f[h])d||"input"==c&&"name"==h.toLowerCase()||setAttribute(b,h,f[h]);if(a.childNodes)for(d=a.childNodes,d="[object Array]"===Object.prototype.toString.call(d)?d:[d],h=0,g=d.length;h<g;h++)if(e=d[h],"[object Array]"===Object.prototype.toString.call(e)?e=DOMBuilder(e[0],e[1]):e.toString()===e&&(e=DOMBuilder(e)),"table"==c&&!1!==a.tableBeautifier&&0!==a.tableBeautifier){var l=b.firstChild,n=e.tagName;-1!="|TBODY|THEAD|TFOOT|".indexOf("|"+n+"|")||8==e.nodeType?b.appendChild(e):"COLGROUP"==n||
"CAPTION"==n?b.insertBefore(e,l):(l&&-1!="|TBODY|THEAD|TFOOT|".indexOf("|"+l.tagName+"|")||(l=b.appendChild(k.createElement("tbody"))),"TR"==n?l.appendChild(e):((f=l.firstChild)&&"TR"==f.tagname||(f=l.appendChild(k.createElement("tr"))),"TD"==n||"TH"==n?f.appendChild(e):((l=f.firstChild)&&"TD"==l.tagName&&"TH"==l.tagName||(l=f.appendChild(k.createElement("td"))),l.appendChild(e))))}else b.appendChild(e);return a.documentFragment||a.fragment?(a=k.createDocumentFragment(),a.appendChild(b),a):b};setAttribute=
function(c,b,a){b=q(b.toLowerCase());if(/^data-/.test(b))c.dataset?c.dataset[y(b.substring(5))]=a:c.setAttribute(b,a);else if(/^on/.test(b)){c.setAttribute(b,a);try{c[b]=new Function(a)}catch(d){}}else if(-1!="|style|class|classname|type|for|htmlfor|".indexOf("|"+b+"|"))switch(b){case "style":c.setAttribute(b,a);c.style.cssText=a;break;case "class":case "classname":if(c.classList){b=a.split(/\s+/g);for(var g=0;g<b.length;g++)c.classList.add(b[g])}else c.className=a;case "type":c.type=a;break;case "for":case "htmlfor":c.htmlFor=
a;break;default:c.setAttribute(b,a,0)}else c.setAttribute(b,a,0)};getName=function(c,b){var a="",d;if(b&&b.attr){d=b.attr;for(var g in d)if("name"==g.toLowerCase()&&d.hasOwnProperty(g))return d[g]}for(p.lastIndex=0;d=p.exec(c);)a=d[1];a&&(a=q(a),d=a.charAt(0),"'"!=d&&'"'!=d||a.charAt(a.length-1)!=d||(a=a.substring(1,a.length-1)));return a};DOMBuilder=function(c,b){c=q(c||"");var a=null;if(!c)return null;t.lastIndex=0;var a=t.exec(c),d=c.charAt(0);if(a&&a[1])d=k.createComment(""),d.nodeValue=a[1];
else if('"'!=d&&"'"!=d||c.charAt(c.length-1)!=d){var a=v.exec(c)||["div"],d=k.createElement(a[0]),g=!1;if("input"==a.toString().toLowerCase()&&r&&(a=getName(c,b)))try{if(d=k.createElement('<input name = "'+a+'" >'),g=!0,"INPUT"!=d.tagName)throw 0;}catch(e){d=k.createElement("input"),d.name=a}for(;a=w.exec(c);)if(a[1])a=a[1].substring(1),d.classList?d.classList.add(a):d.className=d.className?d.className+(" "+a):a;else if(a[2])d.id=a[2].substring(1);else if(a[3])(a=x.exec(a[3]))&&a[1]&&(a=a[1],setAttribute(d,
a,a));else if(a[4]){s.lastIndex=0;var f=s.exec(a[4]),a=(f[1]?"data-":"")+f[2],f=f[3],m=f.charAt(0),p=f.charAt(f.length-1);"'"!=m&&'"'!=m||m!==p||(f=f.substring(1,f.length-1));(!g||"name"!=a.toLowerCase()&&"INPUT"!=d.tagName)&&setAttribute(d,a,f)}}else d=k.createTextNode(c.substring(1,c.length-1));b&&b.toString()===b&&(b={content:b});b&&xCreateElement&&(d=xCreateElement(c,d,b,g));return d};m.DOMBuilder=DOMBuilder})(window);
